alias gst="git status"
alias gfp="git fetch --prune"
alias dc="docker compose"
alias dctest="docker compose run -e RAILS_ENV=test --rm web bundle exec rspec"
alias dbox="docker run -it --rm -v \$(pwd):/development -w /development ruby:3.4.4 bash"
alias tat="tmux attach -t"
alias tlist="tmux list-sessions"
alias tnew="tmux new-session -s"
alias ff="vim -c CtrlP"
alias druby="~/development/dotfiles/docker-ruby.sh"
